# Generated by Django 4.1.10 on 2023-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('instructor_id', models.PositiveIntegerField()),
                ('instructor_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=10)),
                ('credits', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
    ]
