# Generated by Django 4.1.10 on 2023-09-05 22:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0002_studentcourse_delete_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='unique_name',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
