# Generated by Django 4.1.10 on 2023-09-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0004_remove_studentcourse_unique_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='date_and_time',
        ),
    ]
