# Generated by Django 4.1.10 on 2023-09-05 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0008_studentcourse_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='date_and_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 6, 4, 4, 28, 146995)),
        ),
    ]
