# Generated by Django 4.1.10 on 2023-09-05 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0012_remove_studentcourse_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='uuid',
            field=models.PositiveIntegerField(default='', verbose_name=uuid.uuid1),
            preserve_default=False,
        ),
    ]
