# Generated by Django 4.1.10 on 2023-09-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0013_studentcourse_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='uuid',
        ),
    ]
